from __future__ import annotations

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.kc_data_fields import KC_FIELD_DEFINITIONS
from app.infra.models import KcEmployee, KcFieldVisibility

_DEMO_EMPLOYEES: list[dict[str, str | int]] = [
    {
        "department": "Служба поддержки",
        "line": "1",
        "company": "Пари",
        "city": "Ростов-на-Дону",
        "full_name": "Быстров Александр",
        "position": "Оператор 1 линии",
        "grade_new": "2.1",
        "email_new": "a.bystrov@pari.ru",
        "phone": "+7 900 111-22-33",
        "skype": "live:a.bystrov",
        "residence_address": "г. Ростов-на-Дону, ул. Примерная, 12",
        "telegram_username": "@abystrov",
        "account_number": "40817810****1234",
        "telegram_id": "123456789",
        "birth_date": "15.03.1995",
        "first_work_day": "08.05.2023",
        "access_date": "10.05.2023",
        "leave_or_transfer_date": "",
        "photo_url": "https://i.pravatar.cc/400?img=12",
        "sort_order": 10,
    },
    {
        "department": "Служба поддержки",
        "line": "1",
        "company": "Пари",
        "city": "Серпухов",
        "full_name": "Кузьмина Анастасия",
        "position": "Оператор 1 линии",
        "grade_new": "2.0",
        "email_new": "a.kuzmina@pari.ru",
        "phone": "+7 900 222-33-44",
        "skype": "live:a.kuzmina",
        "residence_address": "г. Серпухов, ул. Центральная, 5",
        "telegram_username": "@akuzmina",
        "account_number": "40817810****5678",
        "telegram_id": "234567890",
        "birth_date": "22.07.1998",
        "first_work_day": "12.01.2024",
        "access_date": "15.01.2024",
        "leave_or_transfer_date": "",
        "photo_url": "https://i.pravatar.cc/400?img=32",
        "sort_order": 20,
    },
    {
        "department": "Служба поддержки",
        "line": "2.1",
        "company": "Сквилла",
        "city": "Нижний Новгород",
        "full_name": "Орлов Дмитрий",
        "position": "Специалист 2.1 линии",
        "grade_new": "2.3",
        "email_new": "d.orlov@pari.ru",
        "phone": "+7 900 333-44-55",
        "skype": "live:d.orlov",
        "residence_address": "г. Нижний Новгород, пр. Гагарина, 88",
        "telegram_username": "@dorlov",
        "account_number": "40817810****9012",
        "telegram_id": "345678901",
        "birth_date": "03.11.1994",
        "first_work_day": "20.06.2022",
        "access_date": "22.06.2022",
        "leave_or_transfer_date": "",
        "photo_url": "https://i.pravatar.cc/400?img=15",
        "sort_order": 30,
    },
    {
        "department": "Служба поддержки",
        "line": "2",
        "company": "Пари",
        "city": "Ростов-на-Дону",
        "full_name": "Смирнова Елена",
        "position": "Специалист 2 линии",
        "grade_new": "2.4",
        "email_new": "e.smirnova@pari.ru",
        "phone": "+7 900 444-55-66",
        "skype": "live:e.smirnova",
        "residence_address": "г. Ростов-на-Дону, ул. Садовая, 3",
        "telegram_username": "@esmirnova",
        "account_number": "40817810****3456",
        "telegram_id": "456789012",
        "birth_date": "18.09.1996",
        "first_work_day": "01.03.2021",
        "access_date": "05.03.2021",
        "leave_or_transfer_date": "",
        "photo_url": "https://i.pravatar.cc/400?img=45",
        "sort_order": 40,
    },
    {
        "department": "Служба поддержки",
        "line": "3",
        "company": "Воксис",
        "city": "Серпухов",
        "full_name": "Волкова Мария",
        "position": "Старший специалист 3 линии",
        "grade_new": "2.6",
        "email_new": "m.volkova@pari.ru",
        "phone": "+7 900 555-66-77",
        "skype": "live:m.volkova",
        "residence_address": "г. Серпухов, ул. Лесная, 9",
        "telegram_username": "@mvolkova",
        "account_number": "40817810****7890",
        "telegram_id": "567890123",
        "birth_date": "25.12.1993",
        "first_work_day": "14.08.2019",
        "access_date": "20.08.2019",
        "leave_or_transfer_date": "",
        "photo_url": "https://i.pravatar.cc/400?img=47",
        "sort_order": 50,
    },
    {
        "department": "Служба поддержки",
        "line": "1",
        "company": "Пари",
        "city": "Нижний Новгород",
        "full_name": "Морозов Сергей",
        "position": "Оператор 1 линии",
        "grade_new": "2.2",
        "email_new": "s.morozov@pari.ru",
        "phone": "+7 900 666-77-88",
        "skype": "live:s.morozov",
        "residence_address": "г. Нижний Новгород, ул. Мира, 21",
        "telegram_username": "@smorozov",
        "account_number": "40817810****2468",
        "telegram_id": "678901234",
        "birth_date": "07.02.1997",
        "first_work_day": "03.11.2023",
        "access_date": "06.11.2023",
        "leave_or_transfer_date": "",
        "photo_url": "https://i.pravatar.cc/400?img=52",
        "sort_order": 60,
    },
    {
        "department": "Отдел качества",
        "line": "2",
        "company": "Пари",
        "city": "Ростов-на-Дону",
        "full_name": "Попович Никита",
        "position": "Специалист по качеству",
        "grade_new": "2.5",
        "email_new": "nikita.popovich@pari.ru",
        "phone": "+7 900 777-88-99",
        "skype": "live:n.popovich",
        "residence_address": "г. Ростов-на-Дону, ул. Техническая, 7",
        "telegram_username": "@npopovich",
        "account_number": "40817810****1357",
        "telegram_id": "789012345",
        "birth_date": "10.05.1992",
        "first_work_day": "15.09.2020",
        "access_date": "18.09.2020",
        "leave_or_transfer_date": "",
        "photo_url": "https://i.pravatar.cc/400?img=68",
        "sort_order": 70,
    },
    {
        "department": "Руководство КЦ",
        "line": "3",
        "company": "Пари",
        "city": "Ростов-на-Дону",
        "full_name": "Иванова Ольга",
        "position": "Руководитель смены",
        "grade_new": "3.0",
        "email_new": "o.ivanova@pari.ru",
        "phone": "+7 900 888-99-00",
        "skype": "live:o.ivanova",
        "residence_address": "г. Ростов-на-Дону, ул. Главная, 1",
        "telegram_username": "@oivanova",
        "account_number": "40817810****8642",
        "telegram_id": "890123456",
        "birth_date": "30.01.1990",
        "first_work_day": "01.02.2018",
        "access_date": "05.02.2018",
        "leave_or_transfer_date": "",
        "photo_url": "https://i.pravatar.cc/400?img=25",
        "sort_order": 80,
    },
]


async def seed_kc_data_if_empty(session: AsyncSession) -> None:
    count = (await session.execute(select(func.count()).select_from(KcEmployee))).scalar_one()
    if count == 0:
        for row in _DEMO_EMPLOYEES:
            session.add(KcEmployee(**row))
        await session.commit()

    vis_count = (await session.execute(select(func.count()).select_from(KcFieldVisibility))).scalar_one()
    if vis_count == 0:
        for field in KC_FIELD_DEFINITIONS:
            session.add(
                KcFieldVisibility(
                    field_key=field.key,
                    visible_operator=field.default_operator,
                    visible_supervisor=field.default_supervisor,
                )
            )
        await session.commit()
